### ISSUE TITLE
No longer mapping with OneDrive

### ISSUE THREAD

**Issue by Allistairr** [mardahl/OneDrive-AutoMapper#2]
First of all, thanks for making this fantastic script!  Have been using it for a long time!

Not sure if this is because of recent updates to the OneDrive client or not, but the scripts that were working fine no longer do the actual mapping.  

The detection of Sharepoint libraries is working.  The check for previous sync folders is working.  But, the actual mapping does not.

**Comment by mardahl** [comment]
Hi Allistairr
I have not visited this solution for a long time, so I am not actively maintaining it, but I know a lot of people are using it, so the solution must have been found, without anyone doing a pull request to this repository.
Unfortunately, I don't have the spare time to update the script, but I am available for short term hire to fix any issues if it is critical.
